### ISSUE TITLE
Not working as of 2024-05-26

### ISSUE THREAD

**Issue by ShaunDreclin** [Dreadrith/Unity_NoAutoGame#2]
Unity 2022.3.22f1
NoAutoGame 1.0.1

Entering play mode still auto focuses the game tab

**Comment by Dreadrith** [comment]
This originally didn't work, and I had forgotten to change the main description to only mention closing the game window. It would only close it if the game window didn't exist originally.

Either way, this prompted me to try again, and it worked. Working as of [v1.1.0](https://github.com/Dreadrith/Unity_NoAutoGame/releases/tag/v1.1.0) with a more detailed README.

**Comment by ShaunDreclin** [comment]
Awesome!! Thanks
